<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>PatienceX</AssemblyName>
    <RootNamespace>PatienceX</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>PatienceX.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="PatienceX.ico" />
  </ItemGroup>
</Project>
